apiVersion: v1
kind: ConfigMap
metadata:
  name: web-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Hello ArgoCD</title></head>
    <body>
      <h1>Deployed by Argo CD 🚀</h1>
    </body>
    </html>
