apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: default
  labels:
    app.kubernetes.io/instance: html-app
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
