name: Build and Push HTML App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract short SHA
        id: vars
        run: echo "TAG=$(date +%Y%m%d)-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: tranhoangthaidevops/html-app:${{ env.TAG }}

      - name: Update deployment.yaml with new tag
        run: |
          sed -i "s|\(image: tranhoangthaidevops/html-app:\).*|\1${{ env.TAG }}|" k8s/deployment.yaml

      - name: Commit and push updated deployment.yaml
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${{ env.TAG }}"
          git push
