name: Build and Push HTML App

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract short SHA
        id: vars
        run: echo "TAG=$(date +%Y%m%d)-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: tranhoangthaidevops/html-app:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update deployment.yaml with new tag
        run: |
          set -e
          if [ ! -f k8s/deployment.yaml ]; then
            echo "Error: k8s/deployment.yaml not found"
            exit 1
          fi
          sed -i "s|\(image: tranhoangthaidevops/html-app:\).*|\1${{ env.TAG }}|" k8s/deployment.yaml

      - name: Push changes back to repo
        run: |
          set -e
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/code88-oss/sample-k8s-app.git
          git add .
          git commit -m "Update image tag to ${{ env.TAG }} [skip ci]"
          git push

      - name: Deploy to Minikube
        run: |
          set -e
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo mv minikube-linux-amd64 /usr/local/bin/minikube
          sudo chmod +x /usr/local/bin/minikube
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo mv kubectl /usr/local/bin/
          sudo chmod +x /usr/local/bin/kubectl
          minikube start --driver=docker --cpus=2 --memory=2000mb
          minikube status || { echo "Minikube failed to start"; exit 1; }
          kubectl config use-context minikube
          kubectl apply -f k8s/deployment.yaml
          echo "Listing pods..."
          kubectl get pods -n default -o wide
          echo "Describing pods for deployment 'web'..."
          kubectl describe pod -l app=web -n default || { echo "No pods found with label app=web"; kubectl get pods -n default -o yaml; }
          echo "Checking pod logs..."
          kubectl logs -l app=web -n default || true
          kubectl rollout status deployment/web -n default --timeout=300s || { echo "Rollout failed"; kubectl describe deployment/web -n default; exit 1; }

      - name: Clean up
        if: always()
        run: |
          minikube stop || true
          rm -rf /usr/local/bin/minikube /usr/local/bin/kubectl || true
