name: Build and Push HTML App

on:
  push:
    branches: [master]
  if: github.actor != 'github-actions[bot]'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract short SHA
        id: vars
        run: echo "TAG=$(date +%Y%m%d)-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: tranhoangthaidevops/html-app:${{ env.TAG }}

      - name: Update deployment.yaml with new tag
        run: |
          set -e
          sed -i "s|\(image: tranhoangthaidevops/html-app:\).*|\1${{ env.TAG }}|" k8s/deployment.yaml

      - name: Push changes back to repo
        run: |
          set -e
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token: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@github.com/code88-oss/sample-k8s-app.git
          git add .
          git commit -m "Update image tag to ${{ github.sha }} [skip ci]"
          git push

      - name: Deploy to Minikube
        run: |
          set -e
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo mv minikube-linux-amd64 /usr/local/bin/minikube
          sudo chmod +x /usr/local/bin/minikube
          curl -LO https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl
          sudo mv kubectl /usr/local/bin/
          sudo chmod +x /usr/local/bin/kubectl
          minikube start --driver=docker
          kubectl config use-context minikube
          kubectl apply -f k8s/deployment.yaml
